# server:
#   port: 0

spring:
  application:
    name: a-hello-client
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:9999/uaa/user

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

management:
  security:
    enabled: false
